# Generated by Django 2.2.6 on 2019-10-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Word', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='words',
            new_name='Word',
        ),
    ]
